name: Publish snapshot to GitHub Maven
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
      - run: |
          ls -la
          ls -la .mvn
          echo "-ssettings.gh.xml" > .mvn/maven.config
          cat .mvn/maven.config
          sed -i 's/<build>/<build><finalName>creeperheal2<\/finalName>/' pom.xml
          sed -i 's/<artifactId>CreeperHeal2<\/artifactId>/<artifactId>creeperheal2<\/artifactId>/' pom.xml
      - name: Publish package
        run: |
          mvn versions:set "-DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-SNAPSHOT"
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
